autoload -Uz vcs_info

precmd() {
  vcs_info
}

zstyle ':vcs_info:git:*' formats '%b'

setopt PROMPT_SUBST

PROMPT="(%2~)[${vcs_info_msg_0_}] > "

git-cleanup() {
  git fetch --all --prune
  git branch -vv | grep ": gone]" | awk '{ print $1 }' | xargs -n 1 git branch -d
}

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

